# how many vocab/kanji can show up in a rotating set
max_reviews_at_once = 10

# minimum threshold for fuzzy string matching (decrease for more typing mistakes)
# from 0 - 100
match_score_threshold = 85

# how many times app can write to the database before having to commit
entries_before_commit = 10

# path to sqlite databases
# srs_db contains user data
# full_db contains dictionary data
path_to_srs_db = "./db/srs.db"
path_to_full_db = "./db/KanjiDatabase.sqlite"

# srs review intervals
# after each correct answer, the interval integer increments up 1
# wrong answer, increment down 1
[srs_interval]
0 = { value = 4, unit = "hours" }
1 = { value = 8, unit = "hours" }
2 = { value = 1, unit = "days" }
3 = { value = 3, unit = "days" }
4 = { value = 7, unit = "days" }
5 = { value = 14, unit = "days" }
6 = { value = 30, unit = "days" }
7 = { value = 120, unit = "days" }
8 = { value = -1, unit = "none" } # stop reviewing

[discord]
token_env = "DISCORD_BOT_TOKEN"
command_prefix = "!"